name: CI

on:
  push:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20
        uses: actions/setup-node@master
        with:
          version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
